[theme]
base = "light"
primaryColor = "#221AC8"
backgroundColor = "#C9C8F1"
secondaryBackgroundColor = "#E2E0FA"
textColor = "#2B285F"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"
