[theme]
base = "light"
primaryColor = "#221AC8"
backgroundColor = "#BEBBFB"
secondaryBackgroundColor = "#D3D1FC"
textColor = "#33308F"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"