[theme]
base = "light"
primaryColor = "#3B376E"
backgroundColor = "#F6F5FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D1D2B"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"
